#**Data Preprocessing**
    1. Dataset selection
    2. Selection Libraries
        1. NumPy
        2. Pandas
        3. Matplotlib
        4. sklearn (scikit-learn)
    3. Importing Dataset in Python environment
    4. Missing value
    5. Categorical Data (Dummy value)
    6. Convert dataset in train and test
    7. Normalization of Data

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('/content/Crime_Data_from_2020_to_Present.csv')

In [5]:
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468

In [6]:
X = df.iloc[:,:-1].values # independent
y = df.iloc[:,-1].values # dependent

In [8]:
# Missing value

from sklearn.impute import SimpleImputer
# sklearn.impute.SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

imputer.fit(X[:,1:3])
X[:,1:3]= imputer.transform(X[:,1:3])

In [9]:
X

array([[10304468, '01/08/2020 12:00:00 AM', '01/08/2020 12:00:00 AM',
        ..., '1100 W  39TH                         PL', nan, 34.0141],
       [190101086, '01/02/2020 12:00:00 AM', '01/01/2020 12:00:00 AM',
        ..., '700 S  HILL                         ST', nan, 34.0459],
       [200110444, '04/14/2020 12:00:00 AM', '02/13/2020 12:00:00 AM',
        ..., '200 E  6TH                          ST', nan, 34.0448],
       ...,
       [221005507, '02/10/2022 12:00:00 AM', '02/09/2022 12:00:00 AM',
        ..., '18800    SHERMAN                      WY', nan, 34.2011],
       [221605448, '02/15/2022 12:00:00 AM', '02/14/2022 12:00:00 AM',
        ..., '12700    VAN NUYS                     BL', nan, 34.2755],
       [221018080, '12/25/2022 12:00:00 AM', '12/25/2022 12:00:00 AM',
        ..., '5300    NEWCASTLE                    AV', nan, 34.1667]],
      dtype=object)

In [10]:
from sklearn.compose import ColumnTransformer # sklearn.compose.ColumnTransformer
from sklearn.preprocessing import OneHotEncoder # sklearn.preprocessing.OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,4,5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

ValueError: ignored